---
parent: Api_v1_transfers
name: ApiV1TransfersPostCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/transfers
endpoint: /api/v1/transfers
method: POST
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "confirmed" : false,
      "createdBy" : "{12345}",
      "createdDate" : "{{@Var.createdDate}}",
      "description" : "{{@Var.description}}",
      "id" : "{{@Var.id}}",
      "inactive" : false,
      "location" : "{{@Var.location}}",
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "transactionType" : "{{@Var.transactionType}}",
      "version" : "{{@Var.version}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin != @NULL'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- OWASP-OriginHeaderScrutiny
- OWASP-API7
- Misconfiguration
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
autoGenerated: true
