---
parent: Api_v1_users_enterprise-sign-up
name: ApiV1UsersEnterpriseSignUpPostCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/users/enterprise-sign-up
endpoint: /api/v1/users/enterprise-sign-up
method: POST
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "accountNonExpired" : false,
      "accountNonLocked" : false,
      "company" : "{{@Var.company}}",
      "createdBy" : "{{@Var.createdBy}}",
      "createdDate" : "{{@Var.createdDate}}",
      "credentialsNonExpired" : false,
      "email" : "{{@Var.email}}",
      "enabled" : false,
      "id" : "{{@Var.id}}",
      "inactive" : false,
      "jobTitle" : "{{@Var.jobTitle}}",
      "location" : "{{@Var.location}}",
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "name" : "{{@Var.name}}",
      "password" : "{{@Var.password}}",
      "privileges" : [ "{{@Random}}" ],
      "username" : "{{@Var.username}}",
      "version" : "{{@Var.version}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin != @NULL'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- OWASP-OriginHeaderScrutiny
- OWASP-API7
- Misconfiguration
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
autoGenerated: true
