---
parent: Api_v1_orgs_branchid_users_userid
name: ApiV1OrgsBranchidUsersUseridPutCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/orgs/{branchId}/users/{userId}
endpoint: /api/v1/orgs/{{@Var.branchId}}/users/{{@Var.userId}}
method: PUT
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "createdBy" : "{{@Var.createdBy}}",
      "createdDate" : "{{@Var.createdDate}}",
      "id" : "{{@Var.id}}",
      "inactive" : false,
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "org" : {
        "createdBy" : "{{@Var.createdBy}}",
        "createdDate" : "{{@Var.createdDate}}",
        "id" : "{{@Var.id}}",
        "inactive" : false,
        "modifiedBy" : "{{@Var.modifiedBy}}",
        "modifiedDate" : "{{@Var.modifiedDate}}",
        "name" : "{{@Var.name}}",
        "version" : "{{@Var.version}}"
      },
      "orgRole" : "{{@Var.orgRole}}",
      "status" : "{{@Var.status}}",
      "users" : {
        "company" : "{{@Var.company}}",
        "createdBy" : "{{@Var.createdBy}}",
        "createdDate" : "{{@Var.createdDate}}",
        "email" : "{{@Var.email}}",
        "id" : "{{@Var.id}}",
        "inactive" : false,
        "jobTitle" : "{{@Var.jobTitle}}",
        "location" : "{{@Var.location}}",
        "modifiedBy" : "{{@Var.modifiedBy}}",
        "modifiedDate" : "{{@Var.modifiedDate}}",
        "name" : "{{@Var.name}}",
        "username" : "{{@Var.username}}",
        "version" : "{{@Var.version}}"
      },
      "version" : "{{@Var.version}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin != @NULL'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- OWASP-OriginHeaderScrutiny
- OWASP-API7
- Misconfiguration
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
autoGenerated: true
